import { useState, useMemo } from "react";
import Head from "next/head";
import { atom, useAtom } from "jotai";
import { useHydrateAtoms } from "jotai/utils";

import styles from "../styles/Home.module.css";

interface Pokemon {
  id: number;
  name: string;
  image: string;
}

const pokemonAtom = atom<Pokemon[]>([]);
const filterAtom = atom("");
const filteredPokemon = atom((get) =>
  get(pokemonAtom).filter((pokemon) =>
    pokemon.name.toLowerCase().includes(get(filterAtom).toLowerCase())
  )
);

export async function getServerSideProps() {
  const resp = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );
  return {
    props: {
      initialPokemon: await resp.json(),
    },
  };
}

export default function Home({
  initialPokemon,
}: {
  initialPokemon: Pokemon[];
}) {
  useHydrateAtoms([[pokemonAtom, initialPokemon]] as const);

  const [pokemon] = useAtom(filteredPokemon);
  const [filter, setFilter] = useAtom(filterAtom);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {pokemon.slice(0, 20).map((p) => (
          <div key={p.id} className={styles.image}>
            <img
              alt={p.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
            />
            <h2>{p.name}</h2>
          </div>
        ))}
      </div>
    </div>
  );
}
